### ISSUE TITLE
Error applying PyTorchJob: no matches for kind "PyTorchJob" in version "kubeflow.org/v1alpha1"

### ISSUE THREAD

**Issue by arinto** [kubeflow/pytorch-operator#52] opened 2018-07-26 02:03 UTC
I'm trying to submit PyTorch job, by following Kubeflow [user-guide](https://www.kubeflow.org/docs/about/user_guide/).  However I encountered this error:
```
ERROR handle object: patching object from cluster: merging object with existing state: unable to recognize "/var/folders/fd/h7tg23rd2p3cx7mnp7j47_gw0000gn/T/ksonnet-mergepatch958071722": no matches for kind "PyTorchJob" in version "kubeflow.org/v1alpha1"
```

Any thought on how to move forward? 

Environment: minikube using Kubernetes 1.10

Here's my sequence of command to setup Minikube + Kubeflow
```
minikube stop
minikube delete
minikube start
export KUBEFLOW_KS_DIR=/Volumes/tvlk-repo/github/nvs-kubeflow-poc/kubeflow-ks
export KUBEFLOW_DEPLOY=false
export KUBEFLOW_VERSION=0.2.2
export NAMESPACE=default
curl https://raw.githubusercontent.com/kubeflow/kubeflow/v${KUBEFLOW_VERSION}/scripts/deploy.sh | bash
cd ${KUBEFLOW_KS_DIR}
ks param set kubeflow-core reportUsage false
ks apply default
```
Here's my sequence of command to setup PyTorch:
```
KS_ENV=default
IMAGE=gcr.io/kubeflow-ci/pytorch-dist-mnist_test:1.0
MNIST_JOB_NAME=mnist
ks generate pytorch-job ${MNIST_JOB_NAME} --name=${MNIST_JOB_NAME}
ks param set ${MNIST_JOB_NAME} image ${IMAGE}
ks apply ${KS_ENV} -c ${MNIST_JOB_NAME}
```

kubectl version output
```
ip-10-10-177-11:kubeflow-ks arinto$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jose5918** [comment] 2018-07-26 19:05
@arinto In which command did you encounter this error? Also did you verify that you have the pytorch operator running and the crd created?

https://www.kubeflow.org/docs/started/pytorch/#verify-that-pytorch-support-is-included-in-your-kubeflow-deployment

**Comment by johnugeorge** [comment] 2018-08-01 18:13
@arinto any update?

**Comment by arinto** [comment] 2018-08-02 01:11
Hi @jose5918 and @johnugeorge , I haven't had chance to continue my exploration on Kubeflow + PyTorch. Will update the thread by early next week

**Comment by johnugeorge** [comment] 2018-09-13 09:05
Since this issue is not reproducible, closing this issue
/close

**Closed by johnugeorge** 2018-09-13 09:05 UTC
Labels: community/question
