### ISSUE TITLE
Question: MNIST example

### ISSUE THREAD

**Issue by zzvara** [kubeflow/pytorch-operator#163] opened 2019-05-19 16:40 UTC
While running the MNIST example on a private Kubernetes cluster, I noticed that even when the number-of-workers are set to 30, all of them were scheduled to the same node (where Kubeflow is located due to persistent local storage) and all of them produced the exact same logs. Isn't that indicative of that the same model training ran on 30 different pods at the same time?

I built and pushed the `Dockerfile-mpi` to our private repository and created the `pytorchjob` in CPU mode (uncommenting GPU resource requirements).

**Comment by johnugeorge** [comment] 2019-05-20 02:39
Right. It should to be

**Comment by zzvara** [comment] 2019-05-20 05:22
Then you lost me at the motivation. Why would you run the same training process on the same data in 30 copies, where 1 copy is called the master and 29 copies are called the workers. I checked it is not 04-01.

**Comment by johnugeorge** [comment] 2019-05-20 05:50
I meant, it is a distributed job with 1 master and 30 workers.  You can verify by checking the env variable values in the pods - https://pytorch.org/tutorials/intermediate/dist_tuto.html#initialization-methods

**Comment by johnugeorge** [comment] 2019-06-06 06:12
Duplicate of https://github.com/kubeflow/pytorch-operator/issues/89 
Closing this issue
/close

**Closed by johnugeorge** 2019-06-06 06:12 UTC
